#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : terminaltables
Version  : 3.1.0
Release  : 3
URL      : https://files.pythonhosted.org/packages/9b/c4/4a21174f32f8a7e1104798c445dacdc1d4df86f2f26722767034e4de4bff/terminaltables-3.1.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/9b/c4/4a21174f32f8a7e1104798c445dacdc1d4df86f2f26722767034e4de4bff/terminaltables-3.1.0.tar.gz
Summary  : Generate simple tables in terminals from a nested list of strings.
Group    : Development/Tools
License  : MIT
Requires: terminaltables-python = %{version}-%{release}
Requires: terminaltables-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
==============
terminaltables
==============
Easily draw tables in terminal/console applications from a list of lists of strings. Supports multi-line rows.

%package python
Summary: python components for the terminaltables package.
Group: Default
Requires: terminaltables-python3 = %{version}-%{release}

%description python
python components for the terminaltables package.


%package python3
Summary: python3 components for the terminaltables package.
Group: Default
Requires: python3-core

%description python3
python3 components for the terminaltables package.


%prep
%setup -q -n terminaltables-3.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1549383529
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
